# Generated by Django 4.1.7 on 2023-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teamsite", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
